### ISSUE TITLE
`dependabot_version` and `bundler_version` arguments unused

### ISSUE THREAD

**Issue by banesullivan** [marcoroth/dependabot-bump-together-action#8]
I think that by hard setting these:

https://github.com/marcoroth/dependabot-bump-together-action/blob/ab726ae3405ac60706b35fd8659da2ed009383b6/action.yml#L41-L43

The `dependabot_version` and `bundler_version` arguments are left unused by the action when building the Docker image

**Comment by banesullivan** [comment]
Would it be better to leave these versions out and use the latest versions of these packages?

**Comment by marcoroth** [comment]
The unused arguments were removed in #12. 

It now always uses the latest Dependabot and bundler versions available to build the Docker image.
